### ISSUE TITLE
Idea: set a time of -1 or 0 on error

### ISSUE THREAD

**Issue by yaleman** [Bre77/TA-tcpcheck#1]
It took me far too long to figure out why I was seeing times of ~2.0something seconds on a bunch of my checks 😄 

It'd be handy to be able to filter them out (especially when they're metrics) by being able to filter on `| where time>0` etc.

**Comment by Bre77** [comment]
You can filter out all erronius checks with `error::0`, this would avoid all the cases where the check has timed out.
